//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorro_PrestamosFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUOTAS_PRESTAMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUOTAS_PRESTAMO()
        {
            this.ReporteAtraso = new HashSet<ReporteAtraso>();
        }
    
        public int id_cuota { get; set; }
        public Nullable<int> Cuotas { get; set; }
        public Nullable<System.DateTime> fecha_planificada_pago { get; set; }
        public Nullable<double> Cuota_Mensual { get; set; }
        public Nullable<double> Intereses { get; set; }
        public Nullable<double> Monto_Pagado { get; set; }
        public Nullable<double> Deuda_Capital { get; set; }
        public Nullable<System.DateTime> fecha_efectiva_pago { get; set; }
        public Nullable<double> Abono { get; set; }
        public string modalidad_pago { get; set; }
        public Nullable<int> id_prestamo { get; set; }
    
        public virtual PRESTAMOS PRESTAMOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReporteAtraso> ReporteAtraso { get; set; }
    }
}
