//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorro_PrestamosFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERMEDIA_CLIENTE_ROL
    {
        public int id_intermedia_cliente_rol { get; set; }
        public Nullable<int> id_cliente_intermedia { get; set; }
        public Nullable<int> id_rol_cliente_intermedia { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual ROL_CLIENTES ROL_CLIENTES { get; set; }
    }
}
