//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorro_PrestamosFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AhorrosPrestamosEntities : DbContext
    {
        public AhorrosPrestamosEntities()
            : base("name=AhorrosPrestamosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<CUENTA_BANCARIA> CUENTA_BANCARIA { get; set; }
        public virtual DbSet<CUOTAS_PRESTAMO> CUOTAS_PRESTAMO { get; set; }
        public virtual DbSet<GARANTIA> GARANTIA { get; set; }
        public virtual DbSet<INTERMEDIA_CLIENTE_ROL> INTERMEDIA_CLIENTE_ROL { get; set; }
        public virtual DbSet<INVERSIONES> INVERSIONES { get; set; }
        public virtual DbSet<PAGO_INVERSION> PAGO_INVERSION { get; set; }
        public virtual DbSet<PRESTAMOS> PRESTAMOS { get; set; }
        public virtual DbSet<ROL_CLIENTES> ROL_CLIENTES { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<ReporteAtraso> ReporteAtraso { get; set; }
    }
}
