//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorro_PrestamosFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO_INVERSION
    {
        public int id_cuota_inversion { get; set; }
        public Nullable<System.DateTime> fecha_planificada_pago { get; set; }
        public Nullable<System.DateTime> fecha_efectiva_pago { get; set; }
        public Nullable<double> Monto_Pagado { get; set; }
        public string modalidad_pago { get; set; }
        public Nullable<int> comprobante_pago { get; set; }
        public Nullable<int> id_inversion { get; set; }
    
        public virtual INVERSIONES INVERSIONES { get; set; }
    }
}
