//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorro_PrestamosFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTAMOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRESTAMOS()
        {
            this.CUOTAS_PRESTAMO = new HashSet<CUOTAS_PRESTAMO>();
        }
    
        public int id_prestamo { get; set; }
        public Nullable<int> cliente_prestatario { get; set; }
        public Nullable<int> cliente_fiador { get; set; }
        public Nullable<System.DateTime> fecha_solicitud_prestamo { get; set; }
        public Nullable<System.DateTime> fecha_aprobacion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_termino { get; set; }
        public Nullable<double> monto_prestamo { get; set; }
        public Nullable<double> tasa_interes { get; set; }
        public Nullable<int> Tiempo_Amortizacion_Meses { get; set; }
        public Nullable<double> Total_Prestamo { get; set; }
        public Nullable<bool> aprovado { get; set; }
        public Nullable<int> id_garantia { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual CLIENTES CLIENTES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUOTAS_PRESTAMO> CUOTAS_PRESTAMO { get; set; }
        public virtual GARANTIA GARANTIA { get; set; }
    }
}
