//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorro_PrestamosFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROL_CLIENTES()
        {
            this.INTERMEDIA_CLIENTE_ROL = new HashSet<INTERMEDIA_CLIENTE_ROL>();
        }
    
        public int id_rol_cliente { get; set; }
        public string tipo_rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERMEDIA_CLIENTE_ROL> INTERMEDIA_CLIENTE_ROL { get; set; }
    }
}
